base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path('', views.index, name="index"),
    path('profile/<str:username>/', views.profile, name="profile"),
    path('edit-profile', views.edit_profile, name="edit_profile"),

    path('users/', views.list_all_users, name="user_list"),
    path('users/search/<int:min_elo>/<int:max_elo>/<str:username>', views.list_all_users_search, name="search_users"),

    path('challenges/', views.challenges, name="challenges"),
    path('challenges/delete/<int:id>', views.delete_challenge, name="delete_challenge"),
    path('challenges/accept/<int:id>', views.accept_challenge, name="accept_challenge"),
]

reversi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('users.urls')),
    path('', include('base.urls')),
    path('game/', include('game.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('signup', views.signup, name="signup"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    elo_rating = models.IntegerField(default=1000)
    open_for_challenge = models.BooleanField(default=True)
    bio_text = models.CharField(max_length=2000, default="Hi! I'm new here!")

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth, messages
from .forms import RegistrationForm

# Create your views here.

def signup(req):
    if req.method == 'POST':
        form = RegistrationForm(req.POST)
        if form.is_valid():
            print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = auth.authenticate(username=username, password=password)
            auth.login(req, user)
            messages.success(req, f"Welcome, {username}!")
            return redirect('base:index')
    else:
        form = RegistrationForm()
    return render(req, 'users/register.html', {'form': form})

def login(req):
    if req.method == 'GET':
        form = AuthenticationForm()
        return render(req, 'users/login.html', {'form': form})
    if req.method == 'POST':
        form = AuthenticationForm(request=req, data=req.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(req, user)
                # TODO add a redirect to the index page when it exists
                return redirect('base:index')
        else:
            # rerender with errors
            return render(req, 'users/login.html', {'form': form})

def logout(req):
    auth.logout(req)
    return redirect('users:login')

users/templates/users/login.html
{% extends 'base/base.html' %}

{% block title %} Login {% endblock %}

{% block body %}

<form method="POST" class="d-grid align-items-center justify-content-center">
    {% csrf_token %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}

    {% for field in form %}
    <div class="form-group">
        <b>
            {{ field.label }}
        </b>
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
        <br>
        {{ field }}
    </div>
    {% endfor %}

    <input class="btn btn-primary" type="submit" value="Log In">
    <a href="{% url 'users:signup'%}" class="btn btn-secondary" role="button">Sign Up</a>
</form>

{% endblock %}

users/templates/users/register.html
{% extends 'base/base.html' %}

{% block title %}Signup{% endblock %}

{% block body %}

<form method="POST" class="d-grid align-items-center justify-content-center">
    {% csrf_token %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}

    {% for field in form %}
    <div class="form-group mb-2">
        <b>
            {{ field.label }}
        </b>
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
        <br>
        {{ field }}
    </div>
    {% endfor %}
    <button class="btn btn-primary" type="submit">Register</button>
    <a class="btn btn-secondary" href="{% url 'users:login' %}">Cancel</a>
</form>

{% endblock %}