base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path('', views.index, name="index"),
    path('profile/<str:username>/', views.profile, name="profile"),
    path('edit-profile', views.edit_profile, name="edit_profile"),

    path('users/', views.list_all_users, name="user_list"),
    path('users/search/<int:min_elo>/<int:max_elo>/<str:username>', views.list_all_users_search, name="search_users"),

    path('challenges/', views.challenges, name="challenges"),
    path('challenges/delete/<int:id>', views.delete_challenge, name="delete_challenge"),
    path('challenges/accept/<int:id>', views.accept_challenge, name="accept_challenge"),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path('open_games/<int:page>', views.open_games_list, name="open_games"),
    path('new_open/', views.new_game, name="new_open_game"),
    path('challenge/<str:username>', views.challenge_user, name="challenge_user"),
    path('play/<int:game_id>', views.view_game, name="view_game"),
    path('play/<int:game_id>/<int:row>/<int:col>', views.make_move, name="make_move"),
    path('join/<int:game_id>', views.join_game, name="join_game"),
    path('my_games', views.my_games, name="my_games"),
]

reversi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('users.urls')),
    path('', include('base.urls')),
    path('game/', include('game.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('signup', views.signup, name="signup"),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib import messages
from game.models import Game, Challenge, BoardTemplate

def get_player_games(user, count=-1):
    latest_games = Game.objects.filter(Q(first_player=user) | Q(second_player=user)).order_by('-most_recent_move')

    if count > 0:
        latest_games = latest_games[:count]

    player_role = []
    player_opp = []

    for game in latest_games:
        player_role.append("White" if game.first_player_is_X ^ (game.second_player == user) else "Black")
        player_opp.append(game.first_player if game.second_player == user else game.second_player)

    return list(zip(latest_games, player_role, player_opp))


# Create your views here.

@login_required
def index(req):
    top_players = User.objects.all().order_by('-userdata__elo_rating')[:5]

    latest_games = get_player_games(req.user, 5)

    ctx = {
        'top_players': top_players,
        'latest_games': latest_games,
    }

    return render(req, 'base/index.html', ctx)

@login_required
def profile(req, username):
    user = User.objects.get(username=username)

    ctx = {
        'user': user,
    }

    return render(req, 'base/profile.html', ctx) 

@login_required
def edit_profile(req):
    if req.POST:
        bio = req.POST.get('bio')
        open_challenge = req.POST.get('open-to-challenge') == 'on'

        req.user.userdata.bio_text = bio
        req.user.userdata.open_for_challenge = open_challenge

        req.user.save()

        return redirect('base:profile', username=req.user.username)


    return render(req, 'base/edit_profile.html')

def handle_search(req):
    if req.POST:
        username = req.POST.get("username")
        if username == "":
            username = "*"
        minelo = int(req.POST.get("minelo"))
        maxelo = int(req.POST.get("maxelo"))

        return redirect('base:search_users', min_elo=minelo, max_elo=maxelo, username=username)
    return None

@login_required
def list_all_users(req):

    search = handle_search(req)
    if search is not None:
        return search

    users = User.objects.all().order_by('-userdata__elo_rating')

    ctx = {
        'users': users
    }

    return render(req, 'base/user_list.html', ctx)

@login_required
def list_all_users_search(req, min_elo:int, max_elo:int, username:str):

    search = handle_search(req)
    if search is not None:
        return search

    users = User.objects.filter(userdata__elo_rating__gte=min_elo, userdata__elo_rating__lte=max_elo)
    if username != "*":
        users = users.filter(username__contains=username)
    users = users.order_by('-userdata__elo_rating')

    ctx = {
        'users': users
    }

    return render(req, 'base/user_list.html', ctx)

@login_required
def challenges(req):
    incoming = Challenge.objects.filter(challenged = req.user)
    sent = Challenge.objects.filter(challenger = req.user)

    ctx = {
        'incoming': incoming,
        'sent': sent,
    }


    return render(req, 'base/challenges.html', ctx)

@login_required
def accept_challenge(req, id):
    challenge_exists = True
    try:
        challenge = Challenge.objects.get(id=id)
    except:
        messages.warning(req, "Sorry, that challenge does not exist")
        challenge_exists = False

    if challenge_exists:
        if challenge.challenged == req.user:
            game = Game(
                first_player = challenge.challenger,
                second_player = challenge.challenged,
                first_player_is_X = challenge.challenger_is_X,
                first_players_turn = challenge.challenger_is_X,
                open_game = False,
                board_string = challenge.board_id.board_string,
                board_name = challenge.board_id.name,
                game_started = True
            )

            game.save()
            challenge.delete()

            return redirect('game:view_game', game_id = game.id)


        else:
            messages.warning(req, "Sorry, that challenge isn't for you")
    
    # if we fell through and didn't make it to the create game branch
    return redirect('base:challenges')


@login_required
def delete_challenge(req, id):
    challenge_exists = True
    try:
        challenge = Challenge.objects.get(id=id)
    except:
        messages.warning(req, "Sorry, that challenge does not exist")
        challenge_exists = False

    
    if challenge_exists:
        if challenge.challenger == req.user or challenge.challenged == req.user:
            challenge.delete()
            messages.success(req, "Challenge deleted")
        else:
            messages.warning(req, "You do not have permission to delete that challenge")

    return redirect('base:challenges')

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <link href="{% static 'base/style.css' %}" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        <script src="{% static 'base/onload.js' %}"></script>

        {% block head %}

        {% endblock %}

        <title>
            {% block title %}Reversi Online{% endblock %}
        </title>
    </head>
    <body onload="_onload_handler()">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'base:index' %}">Reversi Online</a>
                <ul class="navbar-nav me-auto nav-pills">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'base:profile' request.user %}">My profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'base:challenges' %}">Challenges</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'game:my_games' %}">My games</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'game:open_games' 1 %}">New game</a>
                    </li>
                    {% endif %}
                </ul>
                
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container-fluid p-3">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}

            <div class="container mt-3">
                {% block body %}

                {% endblock %}
            </div>
        </div>
    </body>
</html>

base/templates/base/challenges.html
{% extends 'base/base.html' %}
{% block title %}Challenges{% endblock %}
{% block body %}
<h1>Challenges</h1>
<div class="float-start" style="width:40%">
    <h2>Incoming challenges</h2>
    <ul class="list-group">
        {% for challenge in incoming %}
        <li class="list-group-item">
            <div class="float-start">
                {% if challenge.challenger_is_X %}Black{% else %}White{% endif %}
                vs {{ challenge.challenger }}
                on {{ challenge.board_id }}
            </div>
            <div class="float-end">
                <a class="btn btn-danger" href="{% url 'base:delete_challenge' challenge.id %}">Decline</a>
                <a class="btn btn-success" href="{% url 'base:accept_challenge' challenge.id %}">Accept</a>
            </div>
        </li>
        {% empty %}
        <li class="list-group-item">Nothing to see here</li>
        {% endfor %}
    </ul>
</div>
<div class="float-end" style="width:40%">
    <h2>Sent challenges</h2>
    <ul class="list-group">
        {% for challenge in sent %}
        <li class="list-group-item">
            <div class="float-start">
                {% if challenge.challenger_is_X %}White{% else %}Black{% endif %}
                vs {{ challenge.challenged }}
                on {{ challenge.board_id }}
            </div>
            <div class="float-end">
                <a class="btn btn-secondary" href="{% url 'base:delete_challenge' challenge.id %}">Cancel</a>
            </div>
        </li>
        {% empty %}
        <li class="list-group-item">Nothing to see here</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

base/templates/base/edit_profile.html
{% extends 'base/base.html' %}

{% block title %} Edit profile {% endblock %}

{% block body %}

<h1>{{ request.user.username }}</h1>

<form method="POST">
    {% csrf_token %}

    <div class="form-group">
        <label for="bio">Bio</label>
        <textarea name="bio" class="form-control">{{ user.userdata.bio_text }}</textarea>
    </div>

    <br>

    <div class="form-check">
        <input type="checkbox" {% if user.userdata.open_for_challenge %} checked {% endif %} name="open-to-challenge" id="open-to-challenge" class="form-check-input">
        <label for="open-to-challenge" class="form-check-label">Open to challenges</label>
    </div>

    <br>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

{% endblock %}

base/templates/base/game_list.html
<ul class="list-group">
    {% for game_data in games %}
    <li class="list-group-item">
        <span class="float-start">
            {{ game_data.1 }} vs. <a href="{% url 'base:profile' game_data.2 %}">{{ game_data.2 }}</a> on {{ game_data.0.board_name }}
        </span>
        <a href="{% url 'game:view_game' game_data.0.id %}" class="btn btn-primary float-end" style="margin-left: 10vw">View</a>
    </li>
    {% empty %}
    <li class="list-group-item">
        <p>Nothing to see here!</p>
    </li>
    {% endfor %}
</ul>

base/templates/base/index.html
{% extends 'base/base.html' %}

{% block body %}

<h1>Reversi Online</h1>
<hr>
<div class="container-fluid">
    <div class="float-start">
        <h2>New game</h2>
        <a class="btn btn-primary" href="{% url 'base:user_list' %}">Challenge</a>
        <a class="btn btn-primary" href="{% url 'game:open_games' 1 %}">Open game</a>
        <hr>
        <h2>Your Games</h2>
        {% include 'base/game_list.html' with games=latest_games %}
        <br>
        <a href="{% url 'game:my_games' %}" class="btn btn-primary">View all</a>
    </div>
    <div class="float-end">
        <h2>Top Players</h2>
        <ol>
            {% for player in top_players %}
            <li>
                <a href="{% url 'base:profile' player.username %}">{{ player.username }}</a> — {{ player.userdata.elo_rating }}
            </li>
            {% endfor %}
        </ol>
    </div>
</div>

{% endblock %}

base/templates/base/profile.html
{% extends 'base/base.html' %}

{% block title %} {{ user.username }}'s profile {% endblock %}

{% block body %}

<h1>{{ user.username }}</h1>
<p>{{ user.userdata.elo_rating }} ELO</p>

{% if request.user == user %}

<a href="{% url 'base:edit_profile' %}" class="btn btn-primary">Edit profile</a>
<p>Challenges {% if user.userdata.open_for_challenge %}open{% else %}closed{% endif %}</p>

{% elif user.userdata.open_for_challenge %}

<a href="{% url 'game:challenge_user' user.username %}" class="btn btn-primary">Challenge</a>

{% endif %}

<hr>
<p>{{ user.userdata.bio_text }}</p>

{% endblock %}

base/templates/base/user_list.html
{% extends 'base/base.html' %}

{% block title %} Users {% endblock %}

{% block body %}

<h1>User list</h1>

<details>
    <summary>Search</summary>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="search-name">Name</label>
            <input class="form-control" id="search-name" name="username">
        </div>
        <div class="form-group">
            <label for="search-minelo">Minimum ELO</label>
            <input type="number" value="0" class="form-control" id="search-minelo" name="minelo">
        </div>
        <div class="form-group">
            <label for="search-maxelo">Maximum ELO</label>
            <input type="number" value="9999" class="form-control" id="search-maxelo" name="maxelo">
        </div>

        <input type="submit" class="btn btn-primary" value="Search">
    </form>
</details>

<hr>

<ul class="list-group">
    {% for user in users %}
    <li class="list-group-item">
        <div class="float-start row" style="width: 50%;">
            <span class="col-6">
                {{ user.username }}
            </span>
            <span class="col-6">
                ELO {{ user.userdata.elo_rating }}
            </span>
        </div>
        <a href="{% url 'base:profile' user.username %}" class="btn btn-primary float-end" style="margin-left: 10vw">Profile</a>
    </li>
    {% empty %}
    <li class="list-group-item">Your search turned up no users.</li>
    {% endfor %}
</ul>

{% endblock %}