base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path('', views.index, name="index"),
    path('profile/<str:username>/', views.profile, name="profile"),
    path('edit-profile', views.edit_profile, name="edit_profile"),

    path('users/', views.list_all_users, name="user_list"),
    path('users/search/<int:min_elo>/<int:max_elo>/<str:username>', views.list_all_users_search, name="search_users"),

    path('challenges/', views.challenges, name="challenges"),
    path('challenges/delete/<int:id>', views.delete_challenge, name="delete_challenge"),
    path('challenges/accept/<int:id>', views.accept_challenge, name="accept_challenge"),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path('open_games/<int:page>', views.open_games_list, name="open_games"),
    path('new_open/', views.new_game, name="new_open_game"),
    path('challenge/<str:username>', views.challenge_user, name="challenge_user"),
    path('play/<int:game_id>', views.view_game, name="view_game"),
    path('play/<int:game_id>/<int:row>/<int:col>', views.make_move, name="make_move"),
    path('join/<int:game_id>', views.join_game, name="join_game"),
    path('my_games', views.my_games, name="my_games"),
]

reversi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('users.urls')),
    path('', include('base.urls')),
    path('game/', include('game.urls')),
]

game/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BoardTemplate(models.Model):
    name = models.CharField(max_length=50)
    # max_length here allows for a 32x32 board
    board_string = models.CharField(max_length=1056)

    def __str__(self):
        return self.name

class Challenge(models.Model):
    challenger = models.ForeignKey(User, on_delete=models.CASCADE, related_name='challenges_sent')
    challenged = models.ForeignKey(User, on_delete=models.CASCADE, related_name='challenges')

    challenger_is_X = models.BooleanField(default=True)
    board_id = models.ForeignKey(BoardTemplate, on_delete=models.CASCADE)

    send_time = models.DateTimeField(auto_now_add=True)


class Game(models.Model):
    first_player = models.ForeignKey(User, on_delete=models.CASCADE, related_name='first_player_in')
    # second is nullable so that an open game can be made
    second_player = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='second_player_in')

    first_player_is_X = models.BooleanField(default=True)
    first_players_turn = models.BooleanField(default=True)

    board_name = models.CharField(max_length=50)
    board_string = models.CharField(max_length=1056)

    open_game = models.BooleanField(default=False)
    game_started = models.BooleanField(default=False)
    game_ended = models.BooleanField(default=False)

    winner = models.CharField(max_length=1, null=True)
    elo_transferred = models.IntegerField(null=True)

    most_recent_move = models.DateTimeField(auto_now_add=True)

    def is_users_turn(self, user):
        if self.game_ended or not self.game_started:
            return False
        if user == self.first_player:
            self.first_players_turn
        elif user == self.second_player:
            return not self.first_players_turn
        return False

game/views.py
from django.shortcuts import render, redirect
from django.http.response import JsonResponse, HttpResponse
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from datetime import datetime

from .models import Game, BoardTemplate, Challenge
from .reversi.reversi import Reversi, _Player, _Winner

def transfer_elo(playerX, playerO, winner:float, k=16):
    # winner == 0 => player X won
    # winner == 1 => player O won
    # winner == 0.5 => tie
    rX = playerX.userdata.elo_rating
    rO = playerO.userdata.elo_rating
    eX = 1 / (1 + (10 ** ( (rO-rX)/400 )))
    eO = 1 / (1 + (10 ** ( (rX-rO)/400 )))

    print("score:",winner)
    print("expected:",eO)

    print("X gets:", k * ((1-winner) - eX))
    print("O gets:", k * (winner - eO))

    playerX.userdata.elo_rating += k * ((1-winner) - eX)
    playerO.userdata.elo_rating += k * (winner - eO)
    playerX.save()
    playerO.save()

    elo_transferred = abs(k * (winner - eO))

    return elo_transferred

def get_game_data(game_list, user):
    role = []
    opponent = []

    for game in game_list:
        if user == game.first_player:
            opponent.append(game.second_player)
            role.append("White")
        else:
            opponent.append(game.first_player)
            role.append("Black")

    return zip(game_list, role, opponent)

# Create your views here.

@login_required
def open_games_list(req, page):
    games = Game.objects.filter(open_game = True, game_started = False).exclude(first_player = req.user)

    paginator = Paginator(games, 30)
    games = paginator.get_page(page)

    ctx = {
        'page': page,
        'games': games
    }

    return render(req, 'game/open_game_list.html', ctx)

@login_required
def new_game(req):

    if req.method == 'POST':
        player_is_X = req.POST.get("play_as") == "white"
        player_goes_first = player_is_X
        board_id = req.POST.get('board')
        board = BoardTemplate.objects.get(id=board_id)


        game = Game(
            first_player = req.user,
            first_player_is_X = player_is_X,
            first_players_turn = player_goes_first,
            open_game = True,
            board_string = board.board_string,
            board_name = board.name
        )
        
        game.save()

        return redirect('game:view_game', game_id = game.id)

    boards = BoardTemplate.objects.all()

    ctx = {
        'boards': boards
    }

    return render(req, 'game/create_game.html', ctx)

@login_required
def challenge_user(req, username:str):
    
    challenged = User.objects.get(username=username)

    if not challenged.userdata.open_for_challenge:
        messages.warning(req, "Sorry, that user isn't open for challenges")
    elif req.method == 'POST':
        if req.user.challenges_sent.filter(challenged=challenged).exists():
            messages.warning(req, "Sorry, you've already sent a request to that user. Please either await their response, or delete it and try again.")
        else:
            player_is_X = req.POST.get("play_as") == "white"
            board_id = req.POST.get('board')
            board = BoardTemplate.objects.get(id=board_id)

            Challenge(
                challenger = req.user,
                challenged = challenged,
                board_id = board,
                challenger_is_X = player_is_X
            ).save()

            return redirect('base:challenges')


    boards = BoardTemplate.objects.all()

    ctx = {
        'boards': boards
    }

    return render(req, 'game/create_game.html', ctx)


@login_required
def view_game(req, game_id):
    game = Game.objects.get(id=game_id)
    turn = game.first_player if game.first_players_turn else game.second_player
    first_player_color = "White" if game.first_player_is_X else "Black"
    second_player_color = "Black" if game.first_player_is_X else "White"
    white_player = game.first_player if game.first_player_is_X else game.second_player
    black_player = game.second_player if game.first_player_is_X else game.first_player

    ctx = {
        'game': game,
        'turn': turn,
        'first_player_color': first_player_color,
        'second_player_color': second_player_color,
        'white_player': white_player,
        'black_player': black_player,
    }

    return render(req, 'game/game.html', ctx)

@login_required
def join_game(req, game_id):
    game = Game.objects.get(id=game_id)

    if game.game_started or game.first_player == req.user:
        prev_page = req.META.get("HTTP_REFERER") or "/"
        messages.warning(req, "Could not join that game")
        return redirect(prev_page)

    game.second_player = req.user
    game.game_started = True

    game.save()

    return redirect('game:view_game', game_id = game.id)


@login_required        
def make_move(req, game_id, row, col):
    game = Game.objects.get(id=game_id)

    if not game.game_ended:

        player_to_move = game.first_player if game.first_players_turn else game.second_player

        if req.user == player_to_move:
            turn = _Player.O if game.first_player_is_X ^ game.first_players_turn else _Player.X
            
            reversi = Reversi.from_board_string(game.board_string, turn)

            try:
                reversi.play_move(row, col)

                game.first_players_turn = (reversi.turn == _Player.O) ^ game.first_player_is_X
                game.most_recent_move = datetime.now()
                game.board_string = str(reversi)

                winner = reversi.get_winner()
                ongoing = winner == _Winner.ONGOING
                if not ongoing:
                    game.game_ended = True

                game_score = 0.5
                if winner == _Winner.O:
                    game_score = 1
                    game.winner = 'o'
                elif winner == _Winner.X:
                    game_score = 0
                    game.winner = 'x'
                elif winner == _Winner.TIE:
                    game_score = 0.5
                    game.winner = 't'


                if not ongoing:
                    if game.first_player_is_X:
                        elo_transferred = transfer_elo(game.first_player, game.second_player, game_score)
                    else:
                        elo_transferred = transfer_elo(game.second_player, game.first_player, game_score)
                    game.elo_transferred = elo_transferred

                game.save()

            except ValueError:
                print("ERROR!")

        

    return redirect('game:view_game', game_id = game_id)


@login_required
def my_games(req):
    my_turn = get_game_data(Game.objects.filter(game_started=True, game_ended=False).filter(Q(first_players_turn=True, first_player=req.user) | Q(first_players_turn=False, second_player=req.user)).order_by('-most_recent_move'), req.user)
    opp_turn = get_game_data(Game.objects.filter(game_started=True, game_ended=False).filter(Q(first_players_turn=True, second_player=req.user) | Q(first_players_turn=False, first_player=req.user)).order_by('-most_recent_move'), req.user)
    finshed = get_game_data(Game.objects.filter(game_ended=True).order_by('-most_recent_move'), req.user)


    ctx = {
        'my_turn': my_turn,
        'opp_turn': opp_turn,
        'finished': finshed,
    }

    return render(req, 'game/my_games.html', ctx)

game/templates/game/create_game.html
{% extends 'base/base.html' %}

{% block title %} New Game {% endblock %}

{% block head %}
<script>
    registerLoadFunction(()=>{
        document.getElementsByName("board")[0].checked = true;
    });
</script>
{% endblock %}

{% block body %}
<h1>New Game</h1>

<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend>I play as...</legend>

        <input type="radio" name="play_as" value="white" id="play_as_white" checked>
        <label for="play_as_white">Play as white</label>
        <br>
        <input type="radio" name="play_as" value="black" id="play_as_black">
        <label for="play_as_black">Play as black</label>
    </fieldset>

    <fieldset class="form-group">
        <legend>Board</legend>

        {% for board in boards %}
        <input type="radio" name="board" value="{{board.id}}" id="board-{{board.id}}">
        <label for="board-{{board.id}}">{{board.name}}</label>
        <br>
        {% endfor %}

    </fieldset>

    <hr>

    <button type="submit" class="btn btn-primary">Create game</button>
</form>
{% endblock %}

game/templates/game/game.html
{% extends 'base/base.html' %}

{% block title %} Play {% endblock %}

{% block head %}
    <style>
        #board
        {
            float: left;
        }
        #info
        {
            float: right;
            border-left: 1px solid black;
            padding: 1em;
        }
        .board-square
        {
            display: inline-block;
            width: 5em;
            height: 5em;
        }
        .board-square a
        {
            width: 100%;
            height: 100%;
            display: block;
        }
        .board-square-white
        {
            background-color: bisque;
        }
        .board-square-black
        {
            background-color: tomato;
        }
        :root
        {
            --stone-size: 75%;
        }
        .stone
        {
            border-radius: 100%;
            width: var(--stone-size);
            height: var(--stone-size);
            margin: calc((100% - var(--stone-size))/2);
            border: 0.25em solid #333;
        }
        .black-stone
        {
            background-color: darkslategrey;
        }
        .white-stone
        {
            background-color: white;
        }
        .board-void
        {
            opacity: 0;
        }
    </style>

    <script>
        const board_string = "{{ game.board_string }}";

        registerLoadFunction(()=>{
            let line_checker_start = true;
            let checker_color = line_checker_start;
            let board = document.getElementById("board");

            let row = document.createElement("tr")
            let rowc = 0;
            let colc = 0;

            for(let c of board_string)
            {
                let div = document.createElement("td");
                div.classList.add("board-square");

                let new_line = false;

                if(c == '_')
                {
                    div.classList.add('board-void');
                }
                else if(c == '.')
                {
                    if(checker_color)
                        div.classList.add('board-square-white');
                    else
                        div.classList.add('board-square-black');
                }
                else if(c == 'x')
                {
                    if(checker_color)
                        div.classList.add('board-square-white');
                    else
                        div.classList.add('board-square-black');

                    let stone = document.createElement("div");
                    stone.classList.add("stone", "white-stone");
                    div.appendChild(stone);

                }
                else if(c == 'o')
                {
                    if(checker_color)
                        div.classList.add('board-square-white');
                    else
                        div.classList.add('board-square-black');

                    let stone = document.createElement("div");
                    stone.classList.add("stone", "black-stone");
                    div.appendChild(stone);

                }
                else
                {
                    new_line = true;
                }


                if(!new_line)
                {
                    checker_color = !checker_color;

                    if(div.childElementCount == 0)
                    {
                        let a = document.createElement("a");
                        a.href = `{{ game.id }}/${rowc}/${colc}`;
                        div.appendChild(a)
                    }

                    row.appendChild(div);


                    rowc++;
                }
                else
                {
                    rowc = 0;
                    colc ++;

                    board.appendChild(row);
                    row = document.createElement('tr')
                    line_checker_start = !line_checker_start;
                    checker_color = line_checker_start;

                }
            }
            board.appendChild(row)
        })
    </script>
{% endblock %}

{% block body %}
<table id="board">

</table>
<div id="info">
    {% if game.second_player is not None %}
        <h1><a href="{% url 'base:profile' game.first_player %}">{{ game.first_player }}</a> vs. <a href="{% url 'base:profile' game.second_player %}">{{ game.second_player }}</a></h1>
        {% if not game.game_ended %}
            <strong>
                {{ turn }}'s turn
                {% if game.first_players_turn %}
                ({{ first_player_color }})
                {% else %}
                ({{ second_player_color }})
                {% endif %}
            </strong>
        {% else %}
            <strong>
                Game over:
                {% if game.winner == 'x' %}
                    {{ white_player }} (White) won
                {% elif game.winner == 'o' %}
                    {{ black_player }} (Black) won
                {% elif game.winner == 't' %}
                    It's a draw
                {% endif %}
            </strong>
            <br>
            <i>
                {{ game.elo_transferred }} ELO transferred.
            </i>
        {% endif %}
    {% else %}
        <strong>Waiting for a second player</strong>
    {% endif %}
</div>
{% endblock %}

game/templates/game/my_games.html
{% extends 'base/base.html' %}
{% block title %}My Games{% endblock %}

{% block body %}
<h1>My games</h1>
<h2>Your turn</h2>
{% include 'base/game_list.html' with games=my_turn %}
<h2>Waiting on opponent</h2>
{% include 'base/game_list.html' with games=opp_turn %}
<h2>Finished</h2>
{% include 'base/game_list.html' with games=finished %}
{% endblock %}

game/templates/game/open_game_list.html
{% extends 'base/base.html' %}

{% block title %} Open Games {% endblock %}

{% block head %}
<style>
    a.disabled
    {
        color: grey;
        text-decoration: none;
        pointer-events: none;
    }
</style>
{% endblock %}

{% block body %}

<h1>Open Games</h1>

<a href="{% url 'game:new_open_game' %}" class="btn btn-primary" aria-role="button">New Game</a>

<hr>

<strong>Page {{page}}</strong>

<ul class="list-group">
    {% for game in games %}
    <li class="list-group-item">
        <span class="float-start">You play as {% if game.first_player_is_X %}Black{% else %}White{% endif %} vs. {{ game.first_player.username }} on {{ game.board_name }}</span>
        <a href="{% url 'game:join_game' game.id %}" class="btn btn-primary float-end">Join</a>
    </li>
    {% endfor %}
</ul>


<a href="1" {% if not games.has_previous %} class="disabled" {% endif %}>First</a>
<a href="{% if games.has_previous %}{{ games.previous_page_number }}{% endif %}" {% if not games.has_previous %} class="disabled" {% endif %}>Previous</a>
Page: {{ games.number }} of {{ games.paginator.num_pages }}
<a href="{% if games.has_next %}{{ games.next_page_number }}{% endif %}" {% if not games.has_next %} class="disabled" {% endif %}>Next</a>
<a href="{{ games.paginator.num_pages }}" {% if not games.has_next %} class="disabled" {% endif %}>Last</a>

{% endblock %}